# Generated by Django 6.0.7 on 2026-09-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lesson_videos_alter_course_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
