# Generated by Django 6.0.7 on 2026-09-29 05:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_is_active_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='videos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='videos'),
        ),
    ]
