# Generated by Django 6.0.7 on 2026-10-02 04:38

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_lesson_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='videos',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='lessons/videos'),
        ),
    ]
