# Generated by Django 6.0.7 on 2026-09-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollement', '0002_enrollement_unique_student_course'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollement',
            name='unique_student_course',
        ),
    ]
