# Generated by Django 6.0.7 on 2026-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
