# Generated by Django 6.0.7 on 2026-09-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_remove_assessment_total_marks_assessmentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='submitted_answers',
            field=models.FileField(blank=True, null=True, upload_to='submissions'),
        ),
    ]
