# Generated by Django 6.0.7 on 2026-09-29 05:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessmentsubmission_submitted_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='submitted_answers',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='submissions'),
        ),
    ]
