# Generated by Django 6.0.7 on 2026-09-29 05:51

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_assessment_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='questions',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='assessment/questions'),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='submitted_answers',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='assessment/submissions'),
        ),
    ]
