# Generated by Django 6.0.7 on 2026-09-29 05:57

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_alter_assessment_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='submitted_answers',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='assessment/submissions'),
        ),
    ]
